spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eventos
    driverClassName: org.postgresql.Driver
    username:
    password:

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
